export type TaskStatus = "Backlog" | "Todo" | "In Progress" | "Review" | "Done"

export type TaskPriority = "Low" | "Medium" | "High" | "Urgent"

export type Task = {
  id: string
  title: string
  project: string
  owner: string
  status: TaskStatus
  priority: TaskPriority
  dueDate: string
  progress: number
}

export const tasks: Task[] = [
  {
    id: "TSK-1001",
    title: "Refresh onboarding analytics",
    project: "Activation",
    owner: "Maya Chen",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-05-28",
    progress: 68,
  },
  {
    id: "TSK-1002",
    title: "Audit billing notification copy",
    project: "Lifecycle",
    owner: "Noah Kim",
    status: "Review",
    priority: "Medium",
    dueDate: "2026-05-30",
    progress: 84,
  },
  {
    id: "TSK-1003",
    title: "Design support queue filters",
    project: "Operations",
    owner: "Ava Patel",
    status: "Todo",
    priority: "High",
    dueDate: "2026-06-03",
    progress: 22,
  },
  {
    id: "TSK-1004",
    title: "Ship regional sales digest",
    project: "Revenue Ops",
    owner: "Ethan Brooks",
    status: "Done",
    priority: "Medium",
    dueDate: "2026-05-22",
    progress: 100,
  },
  {
    id: "TSK-1005",
    title: "Investigate failed export jobs",
    project: "Platform",
    owner: "Lina Torres",
    status: "In Progress",
    priority: "Urgent",
    dueDate: "2026-05-25",
    progress: 46,
  },
  {
    id: "TSK-1006",
    title: "Plan help center migration",
    project: "Docs",
    owner: "Sam Rivera",
    status: "Backlog",
    priority: "Low",
    dueDate: "2026-06-14",
    progress: 8,
  },
  {
    id: "TSK-1007",
    title: "Validate checkout event schema",
    project: "Growth",
    owner: "Grace Lee",
    status: "Review",
    priority: "High",
    dueDate: "2026-05-27",
    progress: 91,
  },
  {
    id: "TSK-1008",
    title: "Prepare incident broadcast template",
    project: "Reliability",
    owner: "Owen Clark",
    status: "Todo",
    priority: "Urgent",
    dueDate: "2026-05-26",
    progress: 18,
  },
  {
    id: "TSK-1009",
    title: "Document account recovery flow",
    project: "Identity",
    owner: "Priya Shah",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2026-06-01",
    progress: 57,
  },
  {
    id: "TSK-1010",
    title: "Review dashboard empty states",
    project: "Design Systems",
    owner: "Leo Martinez",
    status: "Review",
    priority: "Low",
    dueDate: "2026-06-02",
    progress: 76,
  },
  {
    id: "TSK-1011",
    title: "Tune database backup alerts",
    project: "Infrastructure",
    owner: "Hannah Wright",
    status: "Todo",
    priority: "High",
    dueDate: "2026-06-04",
    progress: 12,
  },
  {
    id: "TSK-1012",
    title: "Finalize partner onboarding checklist",
    project: "Partnerships",
    owner: "Marcus Green",
    status: "Backlog",
    priority: "Medium",
    dueDate: "2026-06-08",
    progress: 5,
  },
  {
    id: "TSK-1013",
    title: "Patch webhook retry handling",
    project: "Platform",
    owner: "Nora Evans",
    status: "In Progress",
    priority: "Urgent",
    dueDate: "2026-05-29",
    progress: 63,
  },
  {
    id: "TSK-1014",
    title: "Publish monthly usage report",
    project: "Analytics",
    owner: "Kai Morgan",
    status: "Done",
    priority: "Medium",
    dueDate: "2026-05-24",
    progress: 100,
  },
  {
    id: "TSK-1015",
    title: "Prototype bulk user actions",
    project: "Admin Tools",
    owner: "Ivy Nguyen",
    status: "Todo",
    priority: "High",
    dueDate: "2026-06-06",
    progress: 28,
  },
  {
    id: "TSK-1016",
    title: "Refine invoice export columns",
    project: "Billing",
    owner: "Daniel Park",
    status: "Review",
    priority: "Medium",
    dueDate: "2026-06-05",
    progress: 88,
  },
  {
    id: "TSK-1017",
    title: "Improve onboarding email timing",
    project: "Lifecycle",
    owner: "Sofia Ramirez",
    status: "Backlog",
    priority: "Low",
    dueDate: "2026-06-18",
    progress: 3,
  },
  {
    id: "TSK-1018",
    title: "Add audit log retention banner",
    project: "Compliance",
    owner: "Mason Hill",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-06-07",
    progress: 41,
  },
  {
    id: "TSK-1019",
    title: "Migrate legacy feature flags",
    project: "Platform",
    owner: "Ella Foster",
    status: "Todo",
    priority: "Urgent",
    dueDate: "2026-06-09",
    progress: 16,
  },
  {
    id: "TSK-1020",
    title: "QA mobile navigation states",
    project: "Experience",
    owner: "Ben Carter",
    status: "Review",
    priority: "High",
    dueDate: "2026-06-10",
    progress: 94,
  },
  {
    id: "TSK-1021",
    title: "Clean stale demo accounts",
    project: "Sales Ops",
    owner: "Mila Brown",
    status: "Done",
    priority: "Low",
    dueDate: "2026-05-23",
    progress: 100,
  },
  {
    id: "TSK-1022",
    title: "Map renewal risk segments",
    project: "Customer Success",
    owner: "Julian Scott",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2026-06-11",
    progress: 52,
  },
  {
    id: "TSK-1023",
    title: "Draft self-serve upgrade copy",
    project: "Growth",
    owner: "Chloe Adams",
    status: "Todo",
    priority: "Medium",
    dueDate: "2026-06-13",
    progress: 21,
  },
  {
    id: "TSK-1024",
    title: "Validate permission matrix",
    project: "Security",
    owner: "Aria Nelson",
    status: "Review",
    priority: "Urgent",
    dueDate: "2026-06-12",
    progress: 82,
  },
  {
    id: "TSK-1025",
    title: "Prepare beta feedback summary",
    project: "Product Ops",
    owner: "Theo Phillips",
    status: "Backlog",
    priority: "Medium",
    dueDate: "2026-06-19",
    progress: 9,
  },
  {
    id: "TSK-1026",
    title: "Optimize report loading states",
    project: "Analytics",
    owner: "Ruby Collins",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-06-15",
    progress: 66,
  },
  {
    id: "TSK-1027",
    title: "Update regional tax messaging",
    project: "Billing",
    owner: "Isaac Reed",
    status: "Todo",
    priority: "Medium",
    dueDate: "2026-06-17",
    progress: 24,
  },
  {
    id: "TSK-1028",
    title: "Reconcile CRM sync failures",
    project: "Revenue Ops",
    owner: "Layla Bennett",
    status: "In Progress",
    priority: "Urgent",
    dueDate: "2026-06-16",
    progress: 49,
  },
  {
    id: "TSK-1029",
    title: "Archive deprecated help articles",
    project: "Docs",
    owner: "Miles Turner",
    status: "Done",
    priority: "Low",
    dueDate: "2026-05-21",
    progress: 100,
  },
  {
    id: "TSK-1030",
    title: "Scope workspace invitation limits",
    project: "Identity",
    owner: "Zoe Baker",
    status: "Backlog",
    priority: "High",
    dueDate: "2026-06-21",
    progress: 6,
  },
  {
    id: "TSK-1031",
    title: "Harden file upload validation",
    project: "Security",
    owner: "Caleb Ward",
    status: "Todo",
    priority: "Urgent",
    dueDate: "2026-06-20",
    progress: 31,
  },
  {
    id: "TSK-1032",
    title: "Refresh executive KPI tiles",
    project: "Analytics",
    owner: "Elena Ross",
    status: "Review",
    priority: "Medium",
    dueDate: "2026-06-22",
    progress: 73,
  },
  {
    id: "TSK-1033",
    title: "Set up sandbox billing plans",
    project: "Billing",
    owner: "Finn Hughes",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-06-23",
    progress: 44,
  },
  {
    id: "TSK-1034",
    title: "Review accessibility regressions",
    project: "Experience",
    owner: "Amelia Cooper",
    status: "Todo",
    priority: "High",
    dueDate: "2026-06-24",
    progress: 19,
  },
  {
    id: "TSK-1035",
    title: "Create launch readiness dashboard",
    project: "Product Ops",
    owner: "Ryan Kelly",
    status: "Backlog",
    priority: "Medium",
    dueDate: "2026-06-27",
    progress: 2,
  },
  {
    id: "TSK-1036",
    title: "Resolve API rate limit spikes",
    project: "Reliability",
    owner: "Natalie Gray",
    status: "In Progress",
    priority: "Urgent",
    dueDate: "2026-06-25",
    progress: 58,
  },
  {
    id: "TSK-1037",
    title: "Test new support routing rules",
    project: "Operations",
    owner: "Adam Price",
    status: "Review",
    priority: "Medium",
    dueDate: "2026-06-26",
    progress: 86,
  },
  {
    id: "TSK-1038",
    title: "Plan enterprise SSO rollout",
    project: "Identity",
    owner: "Violet James",
    status: "Backlog",
    priority: "High",
    dueDate: "2026-06-30",
    progress: 11,
  },
]
